server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: orders-service
          uri: ${ORDERS_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/users/*/orders/**
          filters:
            - StripPrefix=1
        - id: payments-service
          uri: ${PAYMENTS_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/users/*/payments/**
          filters:
            - StripPrefix=1
        - id: websocket-orders
          uri: ${ORDERS_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/ws/orders/**
          filters:
            - StripPrefix=1
        - id: orders-swagger
          uri: ${ORDERS_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/swagger-ui/**
          filters:
            - StripPrefix=0
        - id: payments-swagger
          uri: ${PAYMENTS_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/payments-swagger-ui/**
          filters:
            - StripPrefix=0

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 